CUDA_VISIBLE_DEVICES=1 python train.py \
  --base-model LSTM \
  --graph-model \
  --nodal-attention \
  --dropout 0.4 \
  --lr 0.0003 \
  --batch-size 16 \
  --l2 0.00003 \
  --graph_type MMGCN \
  --epochs 20 \
  --graph_construct direct \
  --multi_modal \
  --mm_fusion_mthd concat_subsequently \
  --modals avl \
  --Dataset IEMOCAP \
  --Deep_GCN_nlayers 4 \
  --class-weight \
  --use_speaker \
  --dial_test_path /raid_zoe/home/lr/maokeyu/sign/dial_test_iemocap.pkl \
  --dial_eval_every 1 \
  --dial_save_dir ./saved/dial_eval
